export const INITIAL_TOOLS = [
  // --- Username Domain ---
  {
    name: 'sherlock',
    displayName: 'Sherlock',
    description: 'Hunt down social media accounts by username across 400+ online platforms.',
    category: 'username',
    inputTypes: ['username'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://github.com/sherlock-project/sherlock',
    trackedVersion: '0.14.3',
    license: 'MIT',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'github_recon',
    displayName: 'GitHub Intelligence Recon',
    description: 'Live GitHub user profile intelligence: avatars, public emails, organizations, gists, and repos.',
    category: 'username',
    inputTypes: ['username', 'email'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://github.com/octokit/rest.js',
    trackedVersion: '20.0.2',
    license: 'MIT',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'maigret',
    displayName: 'Maigret Dossier',
    description: 'Collect a dossier on a person by username from 2000+ sites, extracting names, photos, and linked profiles.',
    category: 'username',
    inputTypes: ['username'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://github.com/soxoj/maigret',
    trackedVersion: '0.4.4',
    license: 'GPL-3.0',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'whatsmyname',
    displayName: 'WhatsMyName',
    description: 'Fast username enumeration across hundreds of social networks, forums, and developer communities.',
    category: 'username',
    inputTypes: ['username'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://github.com/WebBreacher/WhatsMyName',
    trackedVersion: '1.2.1',
    license: 'GPL-3.0',
    maintenanceStatus: 'active',
    isEnabled: true,
  },

  // --- Email & Breach Domain ---
  {
    name: 'holehe',
    displayName: 'Holehe',
    description: 'Check if an email address is attached to accounts across 120+ popular web services without notifying target.',
    category: 'email',
    inputTypes: ['email'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://github.com/megadose/holehe',
    trackedVersion: '2.0.2',
    license: 'GPL-3.0',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'ghunt',
    displayName: 'GHunt Google Recon',
    description: 'Offensive Google account OSINT engine for emails, Gaia IDs, YouTube channels, and Google Maps footprints.',
    category: 'email',
    inputTypes: ['email'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://github.com/mxrch/GHunt',
    trackedVersion: '2.1.2',
    license: 'AGPL-3.0',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'h8mail',
    displayName: 'h8mail Breach Intel',
    description: 'Password and breach information gathering tool supporting multi-breach databases and leak parsing.',
    category: 'email',
    inputTypes: ['email'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://github.com/khast3x/h8mail',
    trackedVersion: '2.5.6',
    license: 'BSD-3-Clause',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'theharvester',
    displayName: 'theHarvester',
    description: 'Gather emails, subdomains, hosts, employee names, open ports, and banners from public search engines.',
    category: 'email',
    inputTypes: ['email', 'domain'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://github.com/laramies/theHarvester',
    trackedVersion: '4.4.4',
    license: 'GPL-2.0',
    maintenanceStatus: 'active',
    isEnabled: true,
  },

  // --- Phone Domain ---
  {
    name: 'phoneinfoga',
    displayName: 'PhoneInfoga',
    description: 'Advanced telecom intelligence and OSINT framework for international phone numbers, carrier detection, and social linkages.',
    category: 'phone',
    inputTypes: ['phone'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://github.com/sundowndev/phoneinfoga',
    trackedVersion: '2.10.8',
    license: 'GPL-3.0',
    maintenanceStatus: 'active',
    isEnabled: true,
  },

  // --- Domain / Subdomain / DNS Domain ---
  {
    name: 'domainrecon',
    displayName: 'DomainRecon Live DNS (DoH)',
    description: 'Live Cloudflare DNS-over-HTTPS resolution: A records, MX servers, and security SPF/DMARC policies.',
    category: 'domain',
    inputTypes: ['domain', 'ip'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://github.com/cloudflare/cloudflare-docs',
    trackedVersion: '2.0.0',
    license: 'Apache-2.0',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'crtsh',
    displayName: 'crt.sh Certificate Transparency',
    description: 'Live SSL/TLS Certificate Transparency logs revealing real registered subdomains and certificate authorities.',
    category: 'domain',
    inputTypes: ['domain'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://crt.sh',
    trackedVersion: '1.0.0',
    license: 'Open Access',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'alienvault_otx',
    displayName: 'AlienVault OTX Threat Intel',
    description: 'Live Open Threat Exchange intelligence: passive DNS historical resolutions and malicious threat pulses.',
    category: 'domain',
    inputTypes: ['domain', 'ip'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://otx.alienvault.com',
    trackedVersion: '2.0.0',
    license: 'Open API',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'subfinder',
    displayName: 'Subfinder',
    description: 'Fast passive subdomain discovery tool that discovers valid subdomains using passive online sources.',
    category: 'domain',
    inputTypes: ['domain'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://github.com/projectdiscovery/subfinder',
    trackedVersion: '2.6.5',
    license: 'MIT',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'spiderfoot',
    displayName: 'SpiderFoot Framework',
    description: 'Automate OSINT collection across 200+ modules: IP/DNS peers, BGP routing, PGP keys, and data leaks.',
    category: 'domain',
    inputTypes: ['domain', 'ip', 'email', 'username', 'phone'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://github.com/smicallef/spiderfoot',
    trackedVersion: '4.0.0',
    license: 'MIT',
    maintenanceStatus: 'active',
    isEnabled: true,
  },

  // --- Image Domain ---
  {
    name: 'exiftool',
    displayName: 'ExifTool',
    description: 'Deep metadata extraction engine for digital images, GPS coordinates, timestamps, camera profiles, and device signatures.',
    category: 'image',
    inputTypes: ['image'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://github.com/exiftool/exiftool',
    trackedVersion: '12.70',
    license: 'Artistic / GPL',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'tineye',
    displayName: 'TinEye Reverse Image',
    description: 'Reverse image search engine using image identification technology rather than keywords or metadata.',
    category: 'image',
    inputTypes: ['image'],
    tier: 'tier2',
    executionType: 'link',
    sourceUrl: 'https://tineye.com',
    trackedVersion: '1.0.0',
    license: 'Proprietary',
    maintenanceStatus: 'active',
    isEnabled: true,
  },

  // --- IP / Network Exposure Domain ---
  {
    name: 'ipinfo',
    displayName: 'IPInfo Geolocation & BGP ASN',
    description: 'Live geographic resolution, ISP attribution, Autonomous System (ASN) routes, and coordinates.',
    category: 'ip',
    inputTypes: ['ip', 'domain'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://ipinfo.io',
    trackedVersion: '2.1.0',
    license: 'Open Access',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'shodan_api',
    displayName: 'Shodan Device Exposure',
    description: 'Live internet device scanner detecting open ports, banners, OS versions, and exposed services.',
    category: 'ip',
    inputTypes: ['ip', 'domain'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://www.shodan.io',
    trackedVersion: '2.0.0',
    license: 'Proprietary',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'censys',
    displayName: 'Censys TLS & Certs',
    description: 'Scan hosts and certificates across the IPv4 space for cryptographic fingerprints, cipher suites, and SANs.',
    category: 'ip',
    inputTypes: ['ip', 'domain'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://github.com/censys/censys-python',
    trackedVersion: '2.2.0',
    license: 'Apache-2.0',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'abuseipdb',
    displayName: 'AbuseIPDB Reputation',
    description: 'Live threat database verifying IP addresses associated with malicious activity, spam, and brute force.',
    category: 'ip',
    inputTypes: ['ip', 'domain'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://www.abuseipdb.com',
    trackedVersion: '2.0.0',
    license: 'Proprietary',
    maintenanceStatus: 'active',
    isEnabled: true,
  },

  // --- Dark Web Domain ---
  {
    name: 'ahmia',
    displayName: 'Ahmia Darknet Index',
    description: 'Tor hidden-service search engine index for discovering onion links, leaks, and underground mentions.',
    category: 'domain',
    inputTypes: ['domain', 'email', 'username'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://github.com/ahmia/ahmia-site',
    trackedVersion: '1.4.2',
    license: 'BSD-3-Clause',
    maintenanceStatus: 'active',
    isEnabled: true,
  },

  // --- Phase 21 New Resolvers ---
  {
    name: 'rdap_whois',
    displayName: 'RDAP / WHOIS Inspector',
    description: 'Live IANA/ICANN RDAP registrant inspector: domain creation timestamps, registrar identity, expiry, and authoritative nameservers.',
    category: 'domain',
    inputTypes: ['domain', 'ip'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://rdap.org',
    trackedVersion: '1.0.0',
    license: 'MIT',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'blackbird',
    displayName: 'Blackbird OSINT',
    description: 'High-speed multi-platform social identity reconnaissance and account discovery across 100+ platforms.',
    category: 'username',
    inputTypes: ['username'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://github.com/p1ngul1n0/blackbird',
    trackedVersion: '1.0.4',
    license: 'GPL-3.0',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'ignorant_phone',
    displayName: 'Ignorant Phone Probe',
    description: 'Deep phone number reconnaissance: carrier jurisdiction and messaging platform (WhatsApp, Telegram) active accounts.',
    category: 'phone',
    inputTypes: ['phone'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://github.com/megadose/ignorant',
    trackedVersion: '1.2.0',
    license: 'GPL-3.0',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'onionland',
    displayName: 'OnionLand Darknet Search',
    description: 'Deep darknet engine searching Tor hidden service mirrors, leaked pastebins, and decentralized indices.',
    category: 'domain',
    inputTypes: ['domain', 'email', 'username'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://onionlandsearchengine.com',
    trackedVersion: '1.0.0',
    license: 'MIT',
    maintenanceStatus: 'active',
    isEnabled: true,
  },

  // --- Phase 22 Advanced Cyber IOCs & TLS Deep Resolvers ---
  {
    name: 'threatfox_ioc',
    displayName: 'ThreatFox Malware IOCs',
    description: 'abuse.ch global threat intelligence feed for malware payloads, botnet C2 servers, and cyber adversary IOCs.',
    category: 'domain',
    inputTypes: ['domain', 'ip'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://threatfox.abuse.ch',
    trackedVersion: '1.0.0',
    license: 'CC0-1.0',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'ssl_inspector',
    displayName: 'SSL / TLS Cert Inspector',
    description: 'Direct TLS 1.3 socket handshake extracting Certificate Authority, SAN hostnames, serials, and cryptographic validity.',
    category: 'domain',
    inputTypes: ['domain', 'ip'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://nodejs.org/api/tls.html',
    trackedVersion: '1.0.0',
    license: 'MIT',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'dns_takeover',
    displayName: 'DNS Brute & CNAME Takeover',
    description: 'Subdomain brute-force enumerator with dangling CNAME pointer audit for AWS S3, GitHub Pages, Heroku, Azure, and Vercel.',
    category: 'domain',
    inputTypes: ['domain'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://github.com/tracemesh/dns-takeover',
    trackedVersion: '1.0.0',
    license: 'MIT',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'gpg_keyring',
    displayName: 'OpenPGP Key Server Correlator',
    description: 'Global cryptographic keyring search unmasking real-name aliases, secondary emails, and PGP key fingerprints.',
    category: 'email',
    inputTypes: ['email', 'username', 'domain'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://keyserver.ubuntu.com',
    trackedVersion: '1.0.0',
    license: 'Open Access',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'cloud_bucket',
    displayName: 'Cloud Storage & S3 Bucket Scanner',
    description: 'Autonomous public blob and storage bucket enumerator for AWS S3, Google Cloud Storage, and Azure Blob.',
    category: 'domain',
    inputTypes: ['domain', 'username'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://github.com/tracemesh/cloud-bucket',
    trackedVersion: '1.0.0',
    license: 'MIT',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'security_headers',
    displayName: 'HTTP Security Headers Auditor',
    description: 'Deep inspection of defensive HTTP headers (CSP, HSTS, X-Frame-Options) and server banner fingerprint exposure.',
    category: 'domain',
    inputTypes: ['domain', 'ip'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://github.com/tracemesh/security-headers',
    trackedVersion: '1.0.0',
    license: 'MIT',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'asn_peering',
    displayName: 'BGP Routing & ASN Peering Graph',
    description: 'Autonomous System (ASN) prefix mapper, RIR registrar, and upstream BGP transit peering topology.',
    category: 'ip',
    inputTypes: ['ip', 'domain'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://stat.ripe.net',
    trackedVersion: '1.0.0',
    license: 'Open Access',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'apt_attribution',
    displayName: 'Threat Actor & APT Attribution Engine',
    description: 'Autonomous cyber espionage attribution correlating targets with nation-state APT groups, TTPs, and malware families.',
    category: 'domain',
    inputTypes: ['domain', 'ip', 'email', 'username'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://attack.mitre.org/groups/',
    trackedVersion: '1.0.0',
    license: 'MIT',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'favicon_hash',
    displayName: 'Favicon MurmurHash3 (MMH3) Asset Tracker',
    description: 'Reverse Favicon MMH3 hash calculator and Shodan global internet infrastructure pivot generator.',
    category: 'domain',
    inputTypes: ['domain', 'ip'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://github.com/tracemesh/favicon-hash',
    trackedVersion: '1.0.0',
    license: 'MIT',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'ioc_feed_syncer',
    displayName: 'Real-time IOC Threat Feed Syncer',
    description: 'Real-time cyber threat feed correlation querying ThreatFox, URLhaus, Feodo, and OpenPhish malware IOCs.',
    category: 'domain',
    inputTypes: ['domain', 'ip'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://threatfox.abuse.ch',
    trackedVersion: '1.0.0',
    license: 'CC0-1.0',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'darknet_forums',
    displayName: 'Darknet Marketplace & Forum Hunter',
    description: 'Deep indexed onion search exploring hidden services, underground markets, and breach discussion forums.',
    category: 'email',
    inputTypes: ['email', 'username', 'domain', 'ip'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://ahmia.fi',
    trackedVersion: '1.0.0',
    license: 'Open Access',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'gravatar_unmasker',
    displayName: 'Gravatar Profile & Avatar Unmasker',
    description: 'Cryptographic MD5/SHA-256 avatar hash resolution unmasking display names, verified social links, and public profile bios.',
    category: 'email',
    inputTypes: ['email', 'username'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://gravatar.com',
    trackedVersion: '1.0.0',
    license: 'Open Access',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'github_commit_crawler',
    displayName: 'GitHub Commit & Secret Crawler',
    description: 'Autonomous Git commit log explorer extracting author emails and detecting exposed API credentials in public repos.',
    category: 'username',
    inputTypes: ['username', 'email', 'domain'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://api.github.com',
    trackedVersion: '1.0.0',
    license: 'MIT',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'paste_dump_monitor',
    displayName: 'Pastebin & Leak Repository Monitor',
    description: 'Autonomous dork crawler monitoring Pastebin, Rentry, ControlC, JustPaste, and Gists for leaked credentials.',
    category: 'email',
    inputTypes: ['email', 'domain', 'username', 'ip'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://pastebin.com',
    trackedVersion: '1.0.0',
    license: 'MIT',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'username_fuzzer',
    displayName: 'Username Phonetic & Levenshtein Fuzzer',
    description: 'Multi-platform permutation and leetspeak username generator discovering cross-platform alias variants.',
    category: 'username',
    inputTypes: ['username', 'email'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://github.com/tracemesh/username-fuzzer',
    trackedVersion: '1.0.0',
    license: 'MIT',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'crypto_flow',
    displayName: 'Multi-Chain Crypto Transaction Flow Graph',
    description: 'Autonomous Bitcoin, Ethereum, and Solana blockchain balance, transaction volume, and counterparty mapper.',
    category: 'username',
    inputTypes: ['username', 'email', 'domain'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://blockstream.info',
    trackedVersion: '1.0.0',
    license: 'Open Access',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'ofac_aml_screener',
    displayName: 'OFAC Sanctions & AML Risk Screener',
    description: 'US Treasury OFAC Specially Designated Nationals (SDN) and high-risk crypto mixer address screening engine.',
    category: 'username',
    inputTypes: ['username', 'email', 'domain'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://sanctionssearch.ofac.treas.gov',
    trackedVersion: '1.0.0',
    license: 'Open Access',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'token_graph',
    displayName: 'Smart Contract & Token Distribution Graph',
    description: 'Autonomous EVM smart contract bytecode, deployer originator, and ERC-20 token distribution mapper.',
    category: 'username',
    inputTypes: ['username', 'email', 'domain'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://eth.blockscout.com',
    trackedVersion: '1.0.0',
    license: 'Open Access',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'web3_domains',
    displayName: 'Web3 & Decentralized Domain Resolver',
    description: 'Autonomous forward and reverse resolution for Ethereum ENS (.eth), Unstoppable Domains, and Solana SNS.',
    category: 'domain',
    inputTypes: ['domain', 'username'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://ens.domains',
    trackedVersion: '1.0.0',
    license: 'Open Access',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'ipfs_arweave',
    displayName: 'Decentralized Storage (IPFS / Arweave) Resolver',
    description: 'Immutable content identifier (CID) inspector resolving IPFS and Arweave permaweb storage objects.',
    category: 'domain',
    inputTypes: ['domain', 'username'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://ipfs.io',
    trackedVersion: '1.0.0',
    license: 'Open Access',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
];
