export const INITIAL_TOOLS = [
  // --- Username Domain ---
  {
    name: 'sherlock',
    displayName: 'Sherlock',
    description: 'Hunt down social media accounts by username across 400+ online platforms.',
    category: 'username',
    inputTypes: ['username'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://github.com/sherlock-project/sherlock',
    trackedVersion: '0.14.3',
    license: 'MIT',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'maigret',
    displayName: 'Maigret Dossier',
    description: 'Collect a dossier on a person by username from 2000+ sites, extracting names, photos, and linked profiles.',
    category: 'username',
    inputTypes: ['username'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://github.com/soxoj/maigret',
    trackedVersion: '0.4.4',
    license: 'GPL-3.0',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'whatsmyname',
    displayName: 'WhatsMyName',
    description: 'Fast username enumeration across hundreds of social networks, forums, and developer communities.',
    category: 'username',
    inputTypes: ['username'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://github.com/WebBreacher/WhatsMyName',
    trackedVersion: '1.2.1',
    license: 'GPL-3.0',
    maintenanceStatus: 'active',
    isEnabled: true,
  },

  // --- Email & Breach Domain ---
  {
    name: 'holehe',
    displayName: 'Holehe',
    description: 'Check if an email address is attached to accounts across 120+ popular web services without notifying target.',
    category: 'email',
    inputTypes: ['email'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://github.com/megadose/holehe',
    trackedVersion: '2.0.2',
    license: 'GPL-3.0',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'ghunt',
    displayName: 'GHunt Google Recon',
    description: 'Offensive Google account OSINT engine for emails, Gaia IDs, YouTube channels, and Google Maps footprints.',
    category: 'email',
    inputTypes: ['email'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://github.com/mxrch/GHunt',
    trackedVersion: '2.1.2',
    license: 'AGPL-3.0',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'h8mail',
    displayName: 'h8mail Breach Intel',
    description: 'Password and breach information gathering tool supporting multi-breach databases and leak parsing.',
    category: 'email',
    inputTypes: ['email'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://github.com/khast3x/h8mail',
    trackedVersion: '2.5.6',
    license: 'BSD-3-Clause',
    maintenanceStatus: 'active',
    isEnabled: true,
  },

  // --- Phone Domain ---
  {
    name: 'phoneinfoga',
    displayName: 'PhoneInfoga',
    description: 'Advanced telecom intelligence and OSINT framework for international phone numbers, carrier detection, and social linkages.',
    category: 'phone',
    inputTypes: ['phone'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://github.com/sundowndev/phoneinfoga',
    trackedVersion: '2.10.8',
    license: 'GPL-3.0',
    maintenanceStatus: 'active',
    isEnabled: true,
  },

  // --- Domain / Subdomain / DNS Domain ---
  {
    name: 'domainrecon',
    displayName: 'DomainRecon Passive DNS',
    description: 'Autonomous multi-source DNS enumeration, WHOIS attribution, and ASN routing intelligence engine.',
    category: 'domain',
    inputTypes: ['domain', 'ip'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://github.com/owasp-amass/amass',
    trackedVersion: '4.2.0',
    license: 'Apache-2.0',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'subfinder',
    displayName: 'Subfinder',
    description: 'Fast passive subdomain discovery tool that discovers valid subdomains using passive online sources.',
    category: 'domain',
    inputTypes: ['domain'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://github.com/projectdiscovery/subfinder',
    trackedVersion: '2.6.5',
    license: 'MIT',
    maintenanceStatus: 'active',
    isEnabled: true,
  },

  // --- Image Domain ---
  {
    name: 'exiftool',
    displayName: 'ExifTool',
    description: 'Deep metadata extraction engine for digital images, GPS coordinates, timestamps, camera profiles, and device signatures.',
    category: 'image',
    inputTypes: ['image'],
    tier: 'tier1',
    executionType: 'edge',
    sourceUrl: 'https://github.com/exiftool/exiftool',
    trackedVersion: '12.70',
    license: 'Artistic / GPL',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'tineye',
    displayName: 'TinEye Reverse Image',
    description: 'Reverse image search engine using image identification technology rather than keywords or metadata.',
    category: 'image',
    inputTypes: ['image'],
    tier: 'tier2',
    executionType: 'link',
    sourceUrl: 'https://tineye.com',
    trackedVersion: '1.0.0',
    license: 'Proprietary',
    maintenanceStatus: 'active',
    isEnabled: true,
  },

  // --- IP / Network Exposure Domain ---
  {
    name: 'shodan_api',
    displayName: 'Shodan Device Exposure',
    description: 'Search engine for Internet-connected devices, industrial control systems, and open service ports.',
    category: 'ip',
    inputTypes: ['ip', 'domain'],
    tier: 'tier2',
    executionType: 'link',
    sourceUrl: 'https://www.shodan.io',
    trackedVersion: '1.0.0',
    license: 'Proprietary',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
  {
    name: 'abuseipdb',
    displayName: 'AbuseIPDB Reputation',
    description: 'Verify IP addresses associated with malicious activity, spam, hacking attempts, and botnets.',
    category: 'ip',
    inputTypes: ['ip'],
    tier: 'tier2',
    executionType: 'link',
    sourceUrl: 'https://www.abuseipdb.com',
    trackedVersion: '1.0.0',
    license: 'Proprietary',
    maintenanceStatus: 'active',
    isEnabled: true,
  },
];
